repos:
    # https://black.readthedocs.io/en/stable/index.html
    - repo: https://github.com/psf/black-pre-commit-mirror
      rev: 24.4.2
      hooks:
      - id: black
        language_version: python3.11
      - id: black-jupyter
        files: \.ipynb
        args: [--line-length=77]
    # https://pycqa.github.io/isort/
    - repo: https://github.com/pycqa/isort
      rev: 5.13.2
      hooks:
        - id: isort
          name: isort (python)
          args:
            [--profile=black, --filter-files, --force-sort-within-sections]
